### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by kilbith** [0-afflatus/grailtest#1]
Dear @0-afflatus,

Firstly, thanks for your interest on my mod : [xdecor](https://github.com/kilbith/xdecor).

I notice that you use some of the xdecor's code in your `equipment` and `material` mods. The original code is licensed under GPL version 3, meaning : 
- You must release your mods under GPL version 3 as well (including a copy of the GPLv3 text).
- Credits and link(s) to the sources must be given.

I hope this issue will be fixed as soon as possible.

Textures are WTFPL, credits appreciated but not mandatory.

Regards,
kilbith

**Comment by 0-afflatus** [comment]
Thanks for reporting this @kilbith 
I am happy to separately license the equipment and material mods, I actually prefer GPL3 and only use LGPL2.1 in the rest to follow suit with minetest_game.
If you feel like giving me a precise form of words for the credits and link I'll use it verbatim. Otherwise I'll follow the form of words in xdecor.

**Comment by kilbith** [comment]
Thanks for your comprehension.

For the credits, just the essential is fine (ie. copyright and original sources link).

**Comment by 0-afflatus** [comment]
Having ha a quick look at license compatibility I'm thinking of breaking the GPLv3 stuff back out into a separate mod. That will also make it clear that it's a specific reworking of xdecor for grailtest.

**Comment by 0-afflatus** [comment]
@kilbith feel free to reopen if this requires further changes
